FeynmanICh12Eq1:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanICh12Eq4:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanICh14Eq3:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanICh14Eq4:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanICh18Eq12:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanICh27Eq6:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanICh47Eq23:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanIICh38Eq14:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanIICh38Eq3:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
FeynmanIIICh15Eq27:
  kwargs: null
  noise_rate: 0.0
  output_dir: ./resource/datasets/srsd/1_num/
  output_ext: .txt
  sample_size: 50
